apiVersion: v1
kind: Service
metadata:
  name: wil-app
  namespace: dev
spec:
  type: NodePort
  selector:
    app: wil-app
  ports:
    - protocol: TCP
      port: 8888
      nodePort: 30036
      targetPort: 8888
